# Generated by Django 4.1 on 2024-07-18 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='word',
            field=models.CharField(default=datetime.datetime(2024, 7, 18, 9, 17, 43, 44752, tzinfo=datetime.timezone.utc), max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
